version: "3.3"

services:
  cache:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - LIVE_SERVER_PORT=__LIVE_SERVER_PORT__
      - LISTEN_PORT=__NGINX_LISTEN_PORT__
      - LIVE_SERVER_IP=__LIVE_SERVER_IP__
      - SERVER_NAME=__CACHE_SERVER_FQDN_URL__
    ports:
      - __NGINX_LISTEN_PORT__:80
      - 443:443
      - __LIVE_SERVER_PORT__:30120
    networks:
      - cacheNet
    volumes:
      - cache:/srv/cache

volumes:
  cache:

networks:
  cacheNet:
    driver: bridge
